// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9_gWkyQMS_gdVgN8_8WiMKcBfFWxs3UY',
    appId: '1:1028480647724:web:cf7ab4bc919d46a1a80789',
    messagingSenderId: '1028480647724',
    projectId: 'projet-tikker',
    authDomain: 'projet-tikker.firebaseapp.com',
    databaseURL: 'https://projet-tikker-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'projet-tikker.appspot.com',
    measurementId: 'G-GRJ9P5SSJR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw4pq4ysoVCTY3CzMVFdxI_76TRzbT8WY',
    appId: '1:1028480647724:android:079c1c62097484e1a80789',
    messagingSenderId: '1028480647724',
    projectId: 'projet-tikker',
    databaseURL: 'https://projet-tikker-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'projet-tikker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvRi3uOOFyDmFprE6yPadscVA80GZTHdY',
    appId: '1:1028480647724:ios:ef86bc9988046779a80789',
    messagingSenderId: '1028480647724',
    projectId: 'projet-tikker',
    databaseURL: 'https://projet-tikker-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'projet-tikker.appspot.com',
    iosClientId: '1028480647724-96hbhm4bffjpdaj4hmsbasejtjps4vsd.apps.googleusercontent.com',
    iosBundleId: 'com.example.tikker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvRi3uOOFyDmFprE6yPadscVA80GZTHdY',
    appId: '1:1028480647724:ios:ef86bc9988046779a80789',
    messagingSenderId: '1028480647724',
    projectId: 'projet-tikker',
    databaseURL: 'https://projet-tikker-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'projet-tikker.appspot.com',
    iosClientId: '1028480647724-96hbhm4bffjpdaj4hmsbasejtjps4vsd.apps.googleusercontent.com',
    iosBundleId: 'com.example.tikker',
  );
}
